@startuml

!$UseTheme=C4_FirstTest

!if %variable_exists("RELATIVE_INCLUDE")
  !include ./TestThemeTemplate.puml
!else
  !include https://raw.githubusercontent.com/HyunggyuJang/C4-PlantUML/feature/patch-handwritten-error/percy/TestThemeTemplate.puml
!endif

@enduml
